[package]
name = "particles_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
macroquad = "0.3.24"
egui-macroquad = "0.15"
egui = "0.21"
lerp = "0.4"